version: '3.8'

services:
  chat-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: secure-chat-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    networks:
      - reseau_proxy_npm

networks:
  reseau_proxy_npm:
    external: true
